// INSP AUTO — reference-led automotive editorial minimalism; Inspection Amber, Carbon/Midnight Navy, evidence-first copy, quiet motion.
import { useEffect, type ReactNode } from "react";
import { ArrowUpRight, BadgeCheck, CarFront, FileCheck2, Gauge, LifeBuoy, LockKeyhole, ScanSearch, ShieldCheck, Truck, Waves } from "lucide-react";
import { PAYMENT_LINKS } from "@/lib/paymentLinks";
import { addCartItem, saveCart, type CartItem } from "@/lib/cart";

const serviceCards = [
  ["Car History Report", "A clearer view of the car's recorded past.", CarFront, "/services/car-history-report"],
  ["Motorbike History Report", "Key checks for two-wheel decisions.", Gauge, "/services/motorbike-history-report"],
  ["ATV History Report", "Supporting information for off-road vehicles.", ScanSearch, "/services/atv-history-report"],
  ["Truck History Report", "Keep commercial vehicle history in view.", Truck, "/services/truck-history-report"],
  ["Boat History Report", "Useful records for your next vessel purchase.", Waves, "/services/boat-history-report"],
  ["RV History Report", "Make a larger vehicle purchase with context.", CarFront, "/services/rv-history-report"],
];
const reportItems = ["Vehicle specifications", "Accident information", "Title information", "Safety recalls", "Ownership information", "Lien / finance information", "Vehicle history", "Other available records"];
const serviceVisuals = ["/assets/insp-auto-service-car.jpg", "/assets/insp-auto-service-motorbike.jpg", "/assets/insp-auto-service-atv.jpg", "/assets/insp-auto-service-truck.jpg", "/assets/insp-auto-service-boat.jpg", "/assets/insp-auto-service-rv.jpg"];
const compactPricing = [
  ["Essential Car Report", "Car History Report", "/services/car-history-report"], ["Essential Motorbike Report", "Motorbike History Report", "/services/motorbike-history-report"], ["Essential ATV Report", "ATV History Report", "/services/atv-history-report"], ["Essential Truck Report", "Truck History Report", "/services/truck-history-report"], ["Essential Boat Report", "Boat History Report", "/services/boat-history-report"], ["Essential RV Report", "RV History Report", "/services/rv-history-report"],
] as const;

function go(path: string, id?: string) { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); setTimeout(() => document.getElementById(id || "top")?.scrollIntoView({ behavior: "smooth" }), 10); }
function addReportToCheckout(item: Omit<CartItem, "quantity">) { saveCart(addCartItem([], item)); window.history.pushState({}, "", "/checkout"); window.dispatchEvent(new PopStateEvent("popstate")); window.scrollTo({ top: 0, behavior: "smooth" }); }
function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`reveal ${className}`}>{children}</div>; }

function PricingCard({ name, price, children, href, popular }: { name: string; price: string; children: ReactNode; href: string; popular?: boolean }) {
  return <article className={`pricing-card ${popular ? "popular" : ""}`}>{popular && <span className="popular-badge">Most popular</span>}<div className="pricing-top"><span className="eyebrow">{name}</span><div className="price"><span>£</span>{price}<small> / report</small></div><p>Vehicle History Report</p></div><ul>{children}</ul><button className="button full-button" onClick={() => addReportToCheckout({ id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), name, price: Number(price), href })}>Buy Now <ArrowUpRight size={17} /></button></article>;
}

export default function Home({ initialSection = "home" }: { initialSection?: string }) {
  useEffect(() => { if (initialSection === "pricing") setTimeout(() => document.getElementById("pricing")?.scrollIntoView(), 30); if (initialSection === "services") setTimeout(() => document.getElementById("services")?.scrollIntoView(), 30); const items = document.querySelectorAll(".reveal"); if (typeof IntersectionObserver === "undefined") { items.forEach((item) => item.classList.add("visible")); return; } const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("visible")), { threshold: 0.12 }); items.forEach((item) => observer.observe(item)); return () => observer.disconnect(); }, [initialSection]);
  return <main id="top">
    <section className="hero"><div className="hero-image" /><div className="hero-overlay" /><div className="container hero-content"><Reveal><span className="eyebrow amber">INSP AUTO / UK VEHICLE REPORTS</span><h1>Vehicle history reports <em>you can trust.</em></h1><p>Get detailed vehicle history information before you buy, helping you make a more confident decision.</p><div className="hero-actions"><button className="button" onClick={() => go("/pricing", "pricing")}>Get a Report <ArrowUpRight size={18} /></button><button className="text-button" onClick={() => go("/services", "services")}>Explore Services <span>↓</span></button></div></Reveal></div></section>

    <section className="policy-strip"><div className="container policy-grid policy-reference"><Reveal className="policy-card"><FileCheck2 /><div><h3>Terms &amp; Conditions</h3><ul><li>Reports use information from selected third-party sources.</li><li>Coverage and accuracy can vary by report and source.</li><li>Reports support your checks; they are not a professional inspection.</li><li>Verify the vehicle details independently before purchase.</li></ul><p className="policy-meta">UK-focused service · support@inspauto.com</p><button className="policy-button" onClick={() => go("/terms")}>Read Full Terms <ArrowUpRight size={14} /></button></div></Reveal><Reveal className="policy-card"><ShieldCheck /><div><h3>Refund Policy</h3><ul><li>Contact support if a paid report cannot be fulfilled.</li><li>Incorrect VIN or registration details may affect eligibility.</li><li>Duplicate purchases are reviewed case by case.</li><li>Approved refunds are returned through the original payment route where possible.</li><li>Include your order number when contacting support.</li></ul><button className="policy-button" onClick={() => go("/refund-policy")}>View Refund Policy <ArrowUpRight size={14} /></button></div></Reveal></div></section>

    <section className="other-services-section section-pad"><div className="container other-services-grid"><Reveal className="other-services-rail"><span className="eyebrow">OTHER SERVICES</span>{serviceCards.map(([title, , , href]) => <button key={title as string} onClick={() => go(href as string)}><span>{title as string}</span><ArrowUpRight size={13} /></button>)}</Reveal><Reveal className="company-intro"><span className="eyebrow">INSP AUTO / COMPANY</span><h2>Welcome to INSP AUTO. <em>Discover clearer vehicle history.</em></h2><p>Our reports are designed for people buying used vehicles in the UK. We bring together useful vehicle information in a format that is easier to scan, discuss, and act on before you buy.</p><button className="line-button" onClick={() => go("/about")}>Discover more <ArrowUpRight size={16} /></button></Reveal></div></section>

    <section className="detail-strip section-pad"><div className="container detail-strip-grid"><Reveal><img src="/assets/insp-auto-detail-cockpit.jpg" alt="Modern vehicle cockpit and steering wheel" loading="lazy" /></Reveal><Reveal><img src="/assets/insp-auto-detail-dashboard.jpg" alt="Modern vehicle instrument cluster" loading="lazy" /></Reveal></div><div className="container honest-stats"><div><strong>6</strong><span>Vehicle report types</span></div><div><strong>8</strong><span>Report information areas</span></div><div><strong>£</strong><span>GBP pricing for UK buyers</span></div><div><strong>24/7</strong><span>Support language</span></div></div></section>

    <section className="about-section section-pad"><div className="container about-grid"><Reveal><span className="eyebrow">01 / ABOUT OUR COMPANY</span><h2>Information that helps you ask <em>better questions.</em></h2></Reveal><Reveal className="about-copy"><p>INSP AUTO gives UK vehicle buyers a clearer way to explore a vehicle's recorded past before they commit. Our reports bring useful data together in plain language, so you can decide what to ask, what to verify, and when to take a closer look.</p><button className="line-button" onClick={() => go("/about")}>Discover more <ArrowUpRight size={16} /></button><div className="honest-note"><BadgeCheck size={18} /><span>No invented customer counts. Just useful information and honest limits.</span></div></Reveal></div></section>

    <section id="services" className="services-section section-pad"><div className="container"><Reveal className="section-heading"><div><span className="eyebrow">02 / OUR SERVICES</span><h2>Services we <em>provide.</em></h2></div><p>Choose the vehicle type that matches the purchase in front of you. Each card links to a dedicated report explanation.</p></Reveal><div className="service-grid service-reference-grid">{serviceCards.map(([title, description, Icon, href], index) => { const ServiceIcon = Icon as typeof CarFront; return <Reveal key={title as string} className="service-card" ><span className="card-number">0{index + 1}</span><img className="service-image" src={serviceVisuals[index]} alt={`${title as string} visual`} loading="lazy" /><ServiceIcon className="service-icon" /><h3>{title as string}</h3><p>{description as string}</p><button onClick={() => go(href as string)}>Read More <ArrowUpRight size={14} /></button></Reveal>; })}</div></div></section>

    <section className="affordability-banner"><div className="container"><Reveal><span className="eyebrow amber">INSP AUTO / REPORT OPTIONS</span><h2>Useful detail for a more informed vehicle purchase.</h2><p>Start with the report that matches your vehicle. Checkout is handled securely through the selected payment provider.</p></Reveal></div></section>

    <section id="pricing" className="pricing-section section-pad"><div className="container"><Reveal className="section-heading pricing-heading"><div><span className="eyebrow amber">03 / AFFORDABLE PRICING</span><h2>Affordable <em>pricing.</em></h2></div><p>Every vehicle card starts with the Basic report. Standard and Premium options remain available from the full pricing page.</p></Reveal><div className="compact-pricing-grid">{compactPricing.map(([name, vehicle, href], index) => <Reveal key={name} className="compact-price-card"><span className="compact-label">{vehicle}</span><h3>{name}</h3><div className="compact-price"><span>£</span>56.99</div><small>Vehicle history report</small><ul><li>Vehicle Overview</li><li>Market Value</li><li>Vehicle Specifications</li><li>Accident History</li><li>Title Information</li><li>Safety Recalls</li></ul><button className="compact-buy" onClick={() => addReportToCheckout({ id: `${vehicle.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-basic`, name, price: 56.99, href: PAYMENT_LINKS.basic })}>Buy Now <ArrowUpRight size={13} /></button></Reveal>)}</div><div className="pricing-upgrade"><span>Need more report detail?</span><button className="line-button" onClick={() => go("/pricing")}>Compare Basic, Standard &amp; Premium <ArrowUpRight size={15} /></button></div></div></section>

    <section className="why-section section-pad"><div className="container why-grid"><Reveal className="why-visual"><img src="/assets/insp-auto-report.jpg" alt="Vehicle report folder, clipboard and inspection stamp" loading="lazy" /><span className="visual-caption">A report should make the next question easier.</span></Reveal><Reveal className="why-copy"><span className="eyebrow">04 / WHY CHOOSE INSP AUTO</span><h2>Read the detail without <em>the noise.</em></h2><p>We keep the experience focused on what a buyer can understand and act on: useful records, clear language, and support when a detail needs explaining.</p><div className="feature-list"><div><LockKeyhole /><span><strong>Secure checkout</strong> Payments handled through a trusted payment provider.</span></div><div><ScanSearch /><span><strong>Comprehensive history</strong> Access important information available for your selected report.</span></div><div><LifeBuoy /><span><strong>Customer support</strong> Contact us when you need help understanding the next step.</span></div></div></Reveal></div></section>

    <section className="report-section section-pad"><div className="container report-grid"><Reveal><span className="eyebrow amber">05 / WHAT YOU MAY LEARN</span><h2>Information available in your selected report <em>may include…</em></h2><p>Coverage varies by product and by the records available to the report provider. A report is one part of a careful vehicle purchase.</p></Reveal><Reveal className="report-list">{reportItems.map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong><ArrowUpRight size={16} /></div>)}</Reveal></div></section>

    <section className="process-section section-pad"><div className="container"><Reveal className="section-heading"><div><span className="eyebrow">06 / HOW IT WORKS</span><h2>Three steps to <em>more context.</em></h2></div></Reveal><div className="process-grid"><Reveal><span>01</span><h3>Choose your report</h3><p>Select the report package you need for the vehicle in front of you.</p></Reveal><Reveal><span>02</span><h3>Complete checkout</h3><p>Pay securely through the selected checkout option.</p></Reveal><Reveal><span>03</span><h3>Receive your report</h3><p>Your report is processed and delivered according to the fulfilment process.</p></Reveal></div></div></section>

    <section className="cta-section"><div className="container cta-inner"><span className="stamp">INSP</span><Reveal><span className="eyebrow amber">READY WHEN YOU ARE</span><h2>Ready to check <em>your vehicle?</em></h2><p>Get the information you need before making your next vehicle purchase.</p><button className="button light-button" onClick={() => go("/pricing", "pricing")}>Get Your Report <ArrowUpRight size={18} /></button></Reveal></div></section>
  </main>;
}
